# Commenting your code is very useful.
#baseURL = "./hub/"
title = "TrueNAS Documentation Hub"
enableRobotsTXT = true
relativeURLs = true
disableKinds = ["RSS"]

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
articles = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Google Analytics replaced by Google Tag Manager, which is added directly to the baseof.html files in themes/docsy/layouts/ _default/ and hub/.
# GA disabled by commenting out shortcode in themes/docsy/layouts/partials/head.html.
# Commenting id line only disables the feature described in [params.ui.feedback].
id = "UA-2174408-20"

# Language configuration

[languages]
[languages.en]
description = "Information and how-to articles about TrueNAS software and products."
languageName ="English"
# Weight used for sorting.
weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Everything below this are Site Params

[params]
copyright = "iXsystemsâ„¢"
privacy_policy = "https://www.ixsystems.com/privacy-policy/"

# First one is picked as the Twitter card image if not set on page.
images = ["images/TrueNAS_favicon.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Version"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/freenas/documentation"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
#github_project_repo = ""

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
#gcs_engine_id = "017685261477472164873:k0nt3bphaqi"

# Enable Algolia DocSearch
#algolia_docsearch = true

# Enable Lunr.js offline search
offlineSearch = true

latest = "master"
fullversion = "Current"
version = "Current"
githubbranch = "master"
deprecated = false
currentUrl = "https://truenas.com/docs/hub/"
githubWebsiteRepo = "github.com/freenas/documentation"
githubWebsiteRaw = "raw.githubusercontent.com/freenas/documentation"

# param for displaying an announcement block on every page; see PR #16210
announcement = false
# announcement_message is only displayed when announcement = true; update with your specific message
announcement_message = "The TrueNAS Documentation team hopes you have a great day!"

[taxonomies]
tags = "tags"

[params.ui.readingtime]
enable = true

# Entries for the "Version" dropdown
[[params.versions]]
fullversion = "TrueNAS 12.0"
version = "Current (TN 12.0)"
githubbranch = "master"
url = "/hub/"

[[params.versions]]
fullversion = "TrueNAS 11.3"
version = "TN 11.3"
url = "https://www.ixsystems.com/documentation/truenas/11.3-U3.2/truenas.html"

[[params.versions]]
fullversion = "FreeNAS 11.3"
version = "FN 11.3"
url = "https://www.ixsystems.com/documentation/freenas/11.3-U4/freenas.html"

[[params.versions]]
fullversion = "TrueCommand 1.2"
version = "TC 1.2"
url = "/hub/additional-topics/legacy/tc-legacy-docs/truecommand-1.2/"

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/freenas/documentation/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/freenas/documentation/issues/new">tell us how we can improve</a>.'

# Add dates to content pages
[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":fileModTime", ":default"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

# Add Website Links
[[params.websites]]
	name = "TrueNAS"
	url = "https://www.truenas.com"
[[params.websites]]
	name = "iXsystems"
	url = "https://www.ixsystems.com"
[[params.websites]]
	name = "iX Account Services"
	url = "https://portal.ixsystems.com"
[[params.websites]]
	name = "iX Library"
	url = "https://www.ixsystems.com/library/"
[[params.websites]]
	name = "Community"
	url = "https://www.ixsystems.com/community/"
[[params.websites]]
	name = "Security"
	url = "https://security.ixsystems.com/"
[[params.websites]]
	name = "Blog"
	url = "https://www.ixsystems.com/blog/"
