# Commenting your code is very useful.
# baseURL = "./"
title = "TrueNAS Documentation Hub"
enableRobotsTXT = true
relativeURLs = true


# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
articles = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "UA-2174408-20"

# Language configuration

[languages]
[languages.en]
title = ""
description = "Information and how-to articles about TrueNAS software and products."
languageName ="English"
# Weight used for sorting.
weight = 1
[languages.fr]
contentDir = "content/fr"
languageName = "Français"
weight = 20
#[languages.no]
#title = "Goldydocs"
#description = "Docsy er operativsystem for skyen"
#languageName ="Norsk"
#contentDir = "content/no"
#time_format_default = "02.01.2006"
#time_format_blog = "02.01.2006"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Everything below this are Site Params

[params]
copyright = "iXsystems™"
privacy_policy = "https://www.ixsystems.com/privacy-policy/"

# First one is picked as the Twitter card image if not set on page.
images = ["images/TrueNAS_favicon.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Version"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/freenas/documentation"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
#github_project_repo = ""

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
#gcs_engine_id = "017685261477472164873:k0nt3bphaqi"

# Enable Algolia DocSearch
#algolia_docsearch = true

# Enable Lunr.js offline search
offlineSearch = true

latest = "master"
fullversion = "Current"
version = "Current"
githubbranch = "master"
deprecated = false
currentUrl = "https://docs.ixsystems.com"
githubWebsiteRepo = "github.com/freenas/documentation"
githubWebsiteRaw = "raw.githubusercontent.com/freenas/documentation"

# param for displaying an announcement block on every page; see PR #16210
announcement = false
# announcement_message is only displayed when announcement = true; update with your specific message
announcement_message = "The TrueNAS Documentation team hopes you have a great day!"

[taxonomies]
products = "products"

[[params.versions]]
fullversion = "TrueNAS 12.0-BETA1"
version = "TN 12.0-BETA1"
githubbranch = "master"
url = "./"

[[params.versions]]
fullversion = "TrueNAS 11-3"
version = "TrueNAS 11-3"
url = "/docs/previous-version-documentation/tn-11.3/"

[[params.versions]]
fullversion = "TrueCommand 1.2"
version = "TrueCommand 1.2"
url = "/docs/previous-version-documentation/tc-1.2/"

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/freenas/documentation/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/freenas/documentation/issues/new">tell us how we can improve</a>.'


# Add dates to content pages
[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":fileModTime", ":default"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

# Add Website Links
# Uncomment truenas.com entry when that site is ready
#[[params.websites]]
#	name = "TrueNAS.com"
#	url = "https://www.truenas.com"
[[params.websites]]
	name = "iXsystems"
	url = "https://www.ixsystems.com"
[[params.websites]]
	name = "Library"
	url = "https://www.ixsystems.com/library/"
[[params.websites]]
	name = "Community"
	url = "https://www.ixsystems.com/community/"
[[params.websites]]
	name = "Security"
	url = "https://security.ixsystems.com/"
[[params.websites]]
	name = "Blog"
	url = "https://www.ixsystems.com/blog/"

# Add Topics menu entries
[[params.topics]]
	name = "Home"
	url = "/"
[[params.topics]]
	name = "Overview"
	url = "/docs/intro/"
[[params.topics]]
	name = "Getting Started"
	url = "/docs/initial-setup/"
[[params.topics]]
	name = "Sharing"
	url = "/docs/sharing/"
[[params.topics]]
	name = "Tasks"
	url = "/docs/tasks/"
[[params.topics]]
	name = "Solutions"
	url = "/docs/solutions/"
#[[params.topics]]
#	name = "SCALE"
#	url = "/docs/scale/"
[[params.topics]]
	name = "TrueCommand"
	url = "/docs/truecommand/"
[[params.topics]]
	name = "Hardware"
	url = "/docs/hardware-docs/"
[[params.topics]]
	name = "Additional Topics"
	url = "/docs/additional-topics/"
[[params.topics]]
	name = "Contributing"
	url = "/docs/contributing-docs/"


